## Load NumPy

In [213]:
import numpy as np

In [215]:
 a = np.array([1,2,3,5,8])
print (a.ndim)

1


## The Basics

In [24]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Get Dimension

In [13]:
a.ndim

1

In [14]:
b.ndim

2

## Get Shape

In [15]:
a.shape

(3,)

In [16]:
b.shape

(2, 3)

## Get Type

In [41]:
a.dtype

dtype('int32')

In [42]:
b.dtype

dtype('float64')

## Get Size

In [40]:
a.itemsize

4

In [43]:
b.itemsize

8

## Get Total Size

In [36]:
a.size * a.itemsize

12

In [35]:
a.nbytes

12

In [44]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns, etc.

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
a.shape

(2, 7)

## Get a specific element [r, c]

In [48]:
a[1,5]

13

## Get a specificrow

In [52]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

## Get a specific column

In [53]:
a[:, 2]

array([ 3, 10])

## Getting a little more fancy [startindex:endindex:stepsize]

In [55]:
a[0, 1:-1:2]

array([2, 4, 6])

In [58]:
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


* 3D example

In [59]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Get specific element (work outside inward)

In [64]:
b[1,0,0]

5

## Replace

In [65]:
b[:,1,:] = [[9,9,],[8,8]]

In [66]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [80]:
# All zeros matrix
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
# All 1s matrix

In [82]:
np.ones((2,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [86]:
# Any other number
np.full((2,2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [88]:
# Any other number (Full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [90]:
# Any other number (Full and shape)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [92]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.49474915, 0.2427195 ],
       [0.24884193, 0.68097303],
       [0.43596388, 0.05157866],
       [0.61195015, 0.6658357 ]])

In [93]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.73929528, 0.17156125, 0.01146278, 0.70921687, 0.57546835,
        0.3201927 , 0.17021168],
       [0.78621379, 0.96029598, 0.52590256, 0.53629178, 0.95891403,
        0.5444415 , 0.45087272]])

In [106]:
# Random Integer Values 
np.random.randint(-5,2, size=(3,3))

array([[-1,  0,  1],
       [ 0,  0, -1],
       [-2, -5, -1]])

In [110]:
# Identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [113]:
r2 = np.repeat(arr,3, axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


In [10]:
# Assessment
matrix = np.ones((5,5))
print(matrix)
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [12]:
matrix[1:-1,1:-1] = z
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be carefull when copying arrays!!!

In [16]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 5
print(b)

[5 2 3]


In [17]:
print(a)

[1 2 3]


# Mathematics

In [49]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [48]:
a += 2
a

array([5, 6, 7, 8])

In [23]:
a - 2 

array([-1,  0,  1,  2])

In [24]:
a * 2

array([2, 4, 6, 8])

In [25]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [50]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [51]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [52]:
## Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
## Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [64]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [70]:
# Finde the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [71]:
inv = np.linalg.inv(c)
print(inv)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Statistics

In [75]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [78]:
np.max(stats)

6

In [82]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [93]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

after = before.reshape((4,2))
print(after)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Vertically stacking vectors/matrices

In [95]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### Horizontal Stack

In [100]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [110]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Boolean Maskking and Advanced INdexing

In [112]:
filedata > 5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [114]:
filedata[filedata > 5]

array([6, 7, 8])

### You can Index witn a List in NumPy

In [117]:
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])

In [118]:
np.any(filedata > 5, axis = 0)

array([False,  True,  True,  True])

In [119]:
np.all(filedata > 5, axis = 0)

array([False, False, False, False])

In [121]:
np.any(filedata > 5, axis = 1)

array([False,  True])

In [126]:
((filedata > 5) & (filedata < 8))

array([[False, False, False, False],
       [False,  True,  True, False]])

In [127]:
(~((filedata > 5) & (filedata < 8)))

array([[ True,  True,  True,  True],
       [ True, False, False,  True]])

In [129]:
print(0 * np.nan)

nan


In [132]:
a = np.arange(1,337)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [133]:
print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

9
10


In [136]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\owner\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [148]:
    for i in range(10):
        x[i] = np.random.random(0,10)
    print(x)


TypeError: random() takes at most 1 positional argument (2 given)

In [ ]:
def generator():
    x = np.zeros(10)
    for i in range(10):
        x[i] = np.random.randint(0,10)
    print(x)
generator()

In [149]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)
equal = np.array_equal(a,b)
print(equal)

False
False


In [155]:
import numpy as np
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
c = np.allclose(a, b)
print(c)

[0 0 1 0 0]
[1 1 0 1 0]
False


In [153]:
A = np.random.randint(0,2,5)

B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values

equal = np.allclose(A,B)

print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)

equal = np.array_equal(A,B)

print(equal)

False
False


In [164]:
a = np.random.random(5)
print(a)
a[a.argmax()] = 0
print(a)

[0.68242066 0.55673326 0.00573687 0.5328769  0.09473931]
[0.         0.55673326 0.00573687 0.5328769  0.09473931]


In [161]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.2827852  0.50293528 0.81671884 0.41217271 0.26673604 0.
 0.05192119 0.30153689 0.54986288 0.16585977]


In [165]:
x = np.arange(10)
print(x)
a = np.random.uniform(0,10)
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

[0 1 2 3 4 5 6 7 8 9]
5.146044442852638
5


In [167]:
a = np.arange(10, dtype=np.int32)
print(a)
a = a.astype(np.float32, copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [172]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,0].argsort()])

[[0 4 5]
 [8 2 7]
 [1 6 8]]
[[0 4 5]
 [1 6 8]
 [8 2 7]]


In [180]:
a = np.random.randint(0,3,(3,5))
print(a)
print((~a.any(axis=0)).any())

[[0 1 1 0 2]
 [0 1 0 1 2]
 [1 2 0 2 1]]
False


In [183]:
a = np.array([1,2,3,4,5])
nzeros = 3
Z = np.zeros(len(a) + (len(a)-1)*(nzeros))
Z[::nzeros+1] = a
print(Z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [186]:
a = np.arange(9).reshape(3,3)
print(a)
a[[0,2]] = a[[2,0]]
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [192]:
a = np.random.randint(0,2,10, dtype =bool)
print(a)
np.logical_not(a, out=a)
print(a)
a = np.random.uniform(-1.0,1.0,10)
print(a)
np.negative(a, out=a)
print(a)

[ True False False False  True  True  True False  True  True]
[False  True  True  True False False False  True False False]
[-0.69474529  0.17531809 -0.09290514  0.97289901  0.20846298 -0.83719196
  0.15396712 -0.55078044  0.48422571  0.37467949]
[ 0.69474529 -0.17531809  0.09290514 -0.97289901 -0.20846298  0.83719196
 -0.15396712  0.55078044 -0.48422571 -0.37467949]


In [197]:
a = np.random.randint(0,5,20)
print(a)
print(np.bincount(a).argmax())

[1 1 3 4 2 3 4 2 2 4 2 1 2 2 4 4 0 2 0 2]
2


In [201]:
a = np.arange(20)
np.random.shuffle(a)
n = 5
print(a)
print (a[np.argsort(a)[-n:]])

[15 16  7 11 12 14  8  0  6 17  1 10  5 13  3 18  2  4 19  9]
[15 16 17 18 19]


In [203]:
a = np.random.randint(0,20,20)
print(a)
n = 4
print (a[np.argsort(a)[-n:]])

[ 1  3 19 18  9 10  6 12 17  0  3  2  1 13 15 15  3  0  8 13]
[15 17 18 19]


In [204]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)
array([[1, 0, 0], [2, 3, 4]])

array([[1, 0, 0],
       [2, 3, 4]])

In [241]:
def sumLargestNumbers(list):
    array = np.array(list)
    return (np.sum(array[np.argsort(array)[-2:]]))

print(sumLargestNumbers([1,10]))
print(sumLargestNumbers([1,2,3]))
print(sumLargestNumbers([10,4,34,6,92,2]))

11
5
126


In [261]:
def conditionalSum(values, condition):
    sum = 0;
    if condition == "even":
        cond = 0
    elif condition == "odd":
        cond = 1
    for num in values:
        if (num%2) == cond:
            sum = sum + num
        elif (num%2) == cond:
            sum = sum + num
    return sum     

print(conditionalSum([1, 2, 3, 4, 5], "even"))
print(conditionalSum([1, 2, 3, 4, 5], "odd"))
print(conditionalSum([13, 88, 12, 44, 99], "even"))
print(conditionalSum([], "odd"))

6
9
144
0


In [266]:
def numberOfVowels(data):
    sum = 0
    for letter in data:
        if letter in "aeiouAEIOU":
           sum = sum + 1
    return sum    
    
print(numberOfVowels("orange"))
print(numberOfVowels("lighthouse labs"))
print(numberOfVowels("aeiou"))    

3
5
5


In [312]:
def instructorWithLongestName(instructors):
    longesti = 0
    long = 0
    for i in range(len(instructors)):
        if len(instructors[i].get('name')) > long:
            longesti = i
            long = len(instructors[i].get('name'))
    return instructors[longesti]
   

print(instructorWithLongestName([
  {'name': "Samuel", 'course': "iOS"},
  {'name': "Jeremiah", 'course': "Data"},
  {'name': "Ophilia", 'course': "Web"},
  {'name': "Donald", 'course': "Web"}
]))
print(instructorWithLongestName([
  {'name': "Matthew", 'course': "Data"},
  {'name': "David", 'course': "iOS"},
  {'name': "Domascus", 'course': "Web"}
]))

{'name': 'Jeremiah', 'course': 'Data'}
{'name': 'Domascus', 'course': 'Web'}


In [353]:
def urlEncode(text):
    i = 0
    while i < len(text):
        if text[i] == " " and ((i == 0)):
            text = text[:i] + text[i+1:]                    
        elif (text[i] == " ") and (i == len(text)-1):
            text = text[:i] + text[i+1:]
        elif (text[i] == " ") and ((i != len(text)-2)):
            text = text[:i] + '%20' + text[i+1:]
        else:
            i += 1
    return text

print(urlEncode("Lighthouse Labs"))
print(urlEncode(" Lighthouse Labs  "))
print(urlEncode("blue is greener than purple for sure"))

Lighthouse%20Labs
Lighthouse%20Labs 
blue%20is%20greener%20than%20purple%20for%20sure


In [391]:
def whereCanIPark(spots, vehicle):
    if vehicle == 'regular':
        veh = 'R'
    elif vehicle == 'small':
        veh = 'S'
    elif vehicle == 'motorcycle':
        veh = 'M'
    else:
        return 'error'
    for x in range(len(spots)):
        for y in range(len(spots)):
            spot =  spots[y][x] 
            if veh == spot:
                return ([x,y])
            if veh == 'R' and spot == 'R':
                return ([x,y])
            elif veh == 'S' and (spot == 'R' or spot == 'S'):
                return ([x,y])
            elif veh == 'M' and (spot == 'R' or spot == 'S' or spot == 'M'):
                return ([x,y])
    return ('false')
              
print(whereCanIPark(
  [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ],
  'regular'
))

print(whereCanIPark(
  [
    ['M', 'M', 'M', 'M'],
    ['M', 's', 'M', 'M'],
    ['M', 'M', 'M', 'M'],
    ['M', 'M', 'r', 'M']
  ],
  'small'
))

print(whereCanIPark(
  [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ],
  'motorcycle'
))

[4, 0]
false
[0, 3]


In [396]:
def checkAir(samples, threshold):
    dirty = samples.count('dirty')
    numsamples = len(samples)
    if (dirty/numsamples) < threshold:
        return ('Clean')
    else:
        return ('Polluted')

    
print(checkAir(
  ['clean', 'clean', 'dirty', 'clean', 'dirty', 'clean', 'clean', 'dirty', 'clean', 'dirty'],
  0.3
))

print(checkAir(
  ['dirty', 'dirty', 'dirty', 'dirty', 'clean'],
  0.25
))

print(checkAir(
  ['clean', 'dirty', 'clean', 'dirty', 'clean', 'dirty', 'clean'],
  0.9
))

Polluted
Polluted
Clean


In [437]:
def repeatNumbers(data):
    numlists = len(data)
    list2 = []
    for num in range(numlists):
        list1 = data[num]
        char = str(list1[0])
        mult = list1[1]
        list2.append(char*mult) 
    return ', '.join(list2)
    

print(repeatNumbers([[1, 10]]))
print(repeatNumbers([[1, 2], [2, 3]]))
print(repeatNumbers([[10, 4], [34, 6], [92, 2]]))

1111111111
11, 222
10101010, 343434343434, 9292


In [445]:
def camelCase(input):
    if(len(input) == 0): 
        return
    output = '' 
    output += input[0] 
    for i in range(1, len(input)): 
        if (input[i] == ' '): 
            output += input[i + 1].upper() 
            i += 1
        elif(input[i - 1] != ' '): 
            output += input[i]  
    return(output)  

print(camelCase("this is a string"))
print(camelCase("loopy lighthouse"))
print(camelCase("supercalifragalisticexpialidocious"))

thisIsAString
loopyLighthouse
supercalifragalisticexpialidocious


In [493]:
import numpy as np

def multiplicationTable(maxValue):
    table = np.ones((maxValue,maxValue), dtype = int)
    for x in range(maxValue):
        for y in range(maxValue):
              table[x][y] = (x+1)*(y+1)
    return table

print(multiplicationTable(1))
print(multiplicationTable(5))
print(multiplicationTable(10))

[[1]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
